networks:
  fmi-laravel:
    driver: bridge

volumes:
  pgdata:
    driver: local

services:
  app:
    build:
      args:
        user: fmi-app
        uid: 1000
      context: ./.docker/app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/app
    networks:
      - fmi-laravel
    depends_on:
      db:
        condition: service_healthy

  queues:
    container_name: fmi-queue
    build:
      args:
        user: fmi-app
        uid: 1000
      context: ./.docker/app
    restart: unless-stopped
    volumes:
      - ./:/app
    command: >
      php artisan queue:work database
            --queue=default
            --sleep=3
            --tries=3
            --timeout=120
            --max-time=3600
    networks:
      - fmi-laravel
    depends_on:
      db:
        condition: service_healthy

  db:
    networks:
      - fmi-laravel
    image: pgvector/pgvector:pg18-trixie
    container_name: fmi-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "127.0.0.1:6543:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: pg18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
