networks:
  fmi-laravel:
    driver: bridge

volumes:
  pgdata:
    driver: local

services:
  app:
    build:
      args:
        user: fmi-app
        uid: 1000
      context: ./.docker/app
    restart: unless-stopped
    working_dir: /var/www/
    container_name: fmi-app
    volumes:
      - ./:/var/www
      - ./.docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/app/custom-www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - fmi-laravel

  web:
    image: nginx:alpine
    container_name: fmi-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8065:80"
    networks:
      - fmi-laravel
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d

  queue:
    container_name: fmi-queue
    build:
      args:
        user: fmi-app
        uid: 1000
      context: ./.docker/app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    command: >
      php artisan queue:work database
            --queue=default
            --sleep=3
            --tries=3
            --timeout=120
            --max-time=3600
    networks:
      - fmi-laravel
    depends_on:
      db:
        condition: service_healthy

  db:
    networks:
      - fmi-laravel
    image: pgvector/pgvector:pg18-trixie
    container_name: fmi-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "127.0.0.1:6565:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: pg18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
